#!/bin/bash

function relink {
   mv ~/.$1 ~/.$1.old
   ln -sf ~/dev/vim-env/$1 ~/.$1
}

git submodule init
git submodule update

for file in vim vimrc
do
    relink $file
done

mkdir -p ~/.config/nvim
ln -sf ~/.vimrc ~/.config/nvim/init.vim
